specVersion: 0.0.5
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
features:
  - grafting
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
dataSources:
  - kind: ethereum/contract
    name: PoolAddressesProvider 
    network: {{ network }}
    source:
      address: "{{ PoolAddressesProvider.address }}"
      abi: PoolAddressesProvider
      startBlock: {{ PoolAddressesProvider.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: PoolAddressesProvider
          file: ./abis/PoolAddressesProvider.json
        - name: LoanManager
          file: ./abis/LoanManager.json
        - name: WithdrawalManager
          file: ./abis/WithdrawalManager.json
        - name: PoolConfigurator
          file: ./abis/PoolConfigurator.json
      eventHandlers:
        - event: ProxyCreated(indexed bytes32,indexed address,indexed address)
          handler: handleProxyCreated
      file: ./protocols/isle-finance-v0/src/mapping.ts
templates:
  - kind: ethereum/contract
    name: LoanManager
    network: {{ network }}
    source:
      abi: LoanManager
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: LoanManager
          file: ./abis/LoanManager.json
        - name: PoolConfigurator
          file: ./abis/PoolConfigurator.json
        - name: PoolAddressesProvider
          file: ./abis/PoolAddressesProvider.json
        - name: Pool
          file: ./abis/Pool.json
      eventHandlers:
        - event: Initialized(address)
          handler: handleLoanManagerInitialized
        - event: PaymentAdded(indexed uint16,indexed
            uint256,uint256,uint256,uint256,uint256,uint256)
          handler: handlePaymentAdded
        - event: LoanRepaid(indexed uint16,uint256,uint256)
          handler: handleLoanRepaid
        - event: FeesPaid(indexed uint16,uint256,uint256)
          handler: handleFeesPaid
        - event: IssuanceParamsUpdated(indexed uint48,uint256,uint112)
          handler: handleIssuanceParamsUpdated
      file: ./protocols/isle-finance-v0/src/mapping.ts
  - kind: ethereum/contract
    name: PoolConfigurator
    network: {{ network }}
    source:
      abi: PoolConfigurator
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: PoolConfigurator
          file: ./abis/PoolConfigurator.json
        - name: Pool
          file: ./abis/Pool.json
        - name: WithdrawalManager
          file: ./abis/WithdrawalManager.json
        - name: LoanManager
          file: ./abis/LoanManager.json
        - name: PoolAddressesProvider
          file: ./abis/PoolAddressesProvider.json
      eventHandlers:
        - event: Initialized(indexed address,indexed address,address)
          handler: handlePoolConfiguratorInitialized
        - event: PoolLimitSet(uint104)
          handler: handlePoolLimitSet
        - event: AdminFeeSet(uint256)
          handler: handleAdminFeeSet
        - event: MaxCoverLiquidationSet(uint24)
          handler: handleMaxCoverLiquidationSet
        - event: CoverDeposited(uint256)
          handler: handleCoverDeposited
        - event: CoverWithdrawn(uint256)
          handler: handleCoverWithdrawn
        - event: CoverLiquidated(uint256)
          handler: handleCoverLiquidated
      file: ./protocols/isle-finance-v0/src/mapping.ts
  - kind: ethereum/contract
    name: Pool
    network: {{ network }}
    source:
      abi: Pool
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: Pool
          file: ./abis/Pool.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: ERC20NameBytes
          file: ./abis/ERC20NameBytes.json
        - name: ERC20SymbolBytes
          file: ./abis/ERC20SymbolBytes.json
        - name: PoolConfigurator
          file: ./abis/PoolConfigurator.json
        - name: LoanManager
          file: ./abis/LoanManager.json
      eventHandlers:
      - event: Deposit(indexed address,indexed address,uint256,uint256)
        handler: handleDeposit
      - event: Withdraw(indexed address,indexed address,indexed address,uint256,uint256)
        handler: handleWithdraw
      file: ./protocols/isle-finance-v0/src/mapping.ts
  - kind: ethereum/contract	
    name: WithdrawalManager
    network: {{ network }}
    source:
      abi: WithdrawalManager
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: WithdrawalManager
          file: ./abis/WithdrawalManager.json
        - name: PoolConfigurator
          file: ./abis/PoolConfigurator.json
        - name: PoolAddressesProvider
          file: ./abis/PoolAddressesProvider.json
      eventHandlers:
        - event: Initialized(address,uint256,uint256)
          handler: handleWithdrawalManagerInitialized
      file: ./protocols/isle-finance-v0/src/mapping.ts